/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import control.Control;
import java.awt.BorderLayout;
import java.awt.Toolkit;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.ScrollPaneConstants;
import modelo.personas.clientes.Cliente;

/**
 *
 * @author Laura Alfaro
 */
public class VCatalogoClientes extends javax.swing.JFrame {

    /**
     * Creates new form VCatalogoClientes
     */
    public VCatalogoClientes(Control c) {
        initComponents();
        ctrl = c;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        Busqueda = new javax.swing.JButton();
        Inclusion = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();
        Borrado = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 415, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 211, Short.MAX_VALUE)
        );

        Busqueda.setText("Búsqueda");
        Busqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusquedaActionPerformed(evt);
            }
        });

        Inclusion.setText("Inclusión");
        Inclusion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InclusionActionPerformed(evt);
            }
        });

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        Modificar.setText("Modificación");

        Borrado.setText("Borrado");
        Borrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorradoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("MANTENIMIENTO CLIENTES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Busqueda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Inclusion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Modificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Borrado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clear))
                            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Busqueda)
                    .addComponent(Inclusion)
                    .addComponent(clear)
                    .addComponent(Modificar)
                    .addComponent(Borrado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        panel.removeAll();
        panel.repaint();
    }//GEN-LAST:event_clearActionPerformed

    private void BusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusquedaActionPerformed
        String[] options = {"Opcion", "ID", "Nombre"};
        JComboBox comboBox = new JComboBox(options);
        JLabel label = new JLabel();
        label.setText("Digite y seleccione la opción a buscar:");
        label.setBounds(0, 20, 230, 30);
        comboBox.setBounds(310, 20, 60, 30);
        JTextField txt = new JTextField();
        txt.setBounds(240, 20, 60, 30);
        comboBox.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JComboBox combo = (JComboBox) e.getSource();
                String option = (String) combo.getSelectedItem();
                //busca por cedula
                if ("ID".equals(option)) {
                    String texto = txt.getText();
                    if (ctrl.searchClienteByID(texto) != null) {
                        String nombre = ctrl.searchClienteByID(texto).getNombre();
                        String email = ctrl.searchClienteByID(texto).getEmail();
                        String telefono = ctrl.searchClienteByID(texto).getTelefono();
                        String id = ctrl.searchClienteByID(texto).getCedula();
                        String descuento = Integer.toString(ctrl.searchClienteByID(texto).getDescuento());
                        JTextArea l = new JTextArea();
                        l.setBounds(0, 70, 200, 200);
                        l.setText("NOMBRE: " + nombre + '\n' + "EMAIL: " + email
                                + '\n' + "TELEFONO: " + telefono + '\n' + "CEDULA: " + id
                                + '\n' + "MONTO DESCUENTO: " + descuento);
                        Font font = new Font("Verdana", Font.PLAIN, 12);
                        l.setFont(font);
                        l.setEditable(false);
                        l.setVisible(true);
                        panel.add(l);
                    }
                    if (ctrl.searchClienteByID(texto) == null) {
                        JOptionPane.showMessageDialog(combo, INCORRECT, ERROR, 0);
                    }
                }
                //busca por nombre
                if ("Nombre".equals(option)) {
                    String texto = txt.getText();
                    if (ctrl.searchClienteByName(texto) != null) {
                        JTextArea l = new JTextArea();

                        for (Cliente cliente : ctrl.searchClienteByName(texto)) {
                            String nombre = cliente.getNombre();
                            String email = cliente.getEmail();
                            String telefono = cliente.getTelefono();
                            String id = cliente.getCedula();
                            String descuento = Integer.toString(cliente.getDescuento());
                            l.append("NOMBRE: " + nombre + '\n' + "EMAIL: " + email
                                    + '\n' + "TELEFONO: " + telefono + '\n' + "CEDULA: " + id
                                    + '\n' + "MONTO DESCUENTO: " + descuento);
                        }
                        Font font = new Font("Verdana", Font.PLAIN, 12);
                        l.setFont(font);
                        l.setEditable(false);
                        l.setVisible(true);
                        JScrollPane scroll = new JScrollPane(l);  //no sirve 
                        l.setBounds(0, 70, 200, 200);
                        scroll.setVisible(true);
                        scroll.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
                        panel.add(l);
                    }
                } else {
                    JOptionPane.showMessageDialog(combo, INCORRECT, ERROR, 0);
                }
            }
        }
        );
        panel.add(label);
        panel.add(comboBox);
        panel.add(txt);
        panel.repaint();
    }//GEN-LAST:event_BusquedaActionPerformed

    private void InclusionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InclusionActionPerformed
        addLabels();
        JOptionPane.showMessageDialog(this, MENSSAGE, ADVICE, 1);
        JTextField nom = addTextField(60, 20, 60, 20);
        JTextField ced = addTextField(60, 80, 60, 20);
        JTextField tel = addTextField(80, 60, 80, 20);
        JTextField em = addTextField(60, 40, 60, 20);
        JTextField des = addTextField(120, 100, 40, 20);
        JButton insertar = new JButton();
        insertar.setBounds(20, 140, 100, 20);
        insertar.setVisible(true);
        insertar.setText("Insertar");
        panel.add(insertar);
        insertar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (nom.getText().length() == 0 || em.getText().length() == 0
                        || tel.getText().length() == 0 || ced.getText().length() == 0 || des.getText().length() == 0) {
                    JOptionPane.showMessageDialog(insertar, "NO DEJE CASILLAS EN BLANCO", ADVICE, 0);
                } else {
                    String nombre = nom.getText();
                    String email = em.getText();
                    String cedula = ced.getText();
                    String telefono = tel.getText();
                    int descuento = Integer.parseInt(des.getText());
                    Cliente cliente = ctrl.createCLiente(cedula, nombre, telefono, email, descuento);
                    try {
                        ctrl.addCliente(cliente);
                        JOptionPane.showMessageDialog(insertar, "Cliente insertado", ADVICE, 1);
                    } catch (Exception ex) {

                    }
                }
            }
        });

        panel.repaint();

    }//GEN-LAST:event_InclusionActionPerformed

    private void BorradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorradoActionPerformed
        JLabel borrar = new JLabel("Digite la cedula del cliente a borrar :");
        borrar.setBounds(100, 20, 260, 20);
        JTextField ced = new JTextField();
        ced.setBounds(120, 40, 100, 20);
        JButton b = new JButton("Borrar");
        b.setBounds(120, 80, 100, 30);
        b.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (ced.getText().length() == 0) {
                    JOptionPane.showMessageDialog(b, "LA CASILLA ESTA EN BLANCO", ADVICE, 0);
                } else {
                    String id = ced.getText();
                    try {
                        ctrl.deleteCliente(id);
                        JOptionPane.showMessageDialog(b, "Cliente borrado", ADVICE, 1);
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(b, "Cliente inexistente", ERROR, 0);
                    }
                }
            }
        });
        panel.add(b);
        panel.add(borrar);
        panel.add(ced);
        panel.repaint();
    }//GEN-LAST:event_BorradoActionPerformed
    public JTextField addTextField(int x, int y, int m, int u) {
        JTextField nom = new JTextField();
        nom.setBounds(x, y, m, u);
        panel.add(nom);
        return nom;
    }

    public void addLabels() {
        JLabel nom = new JLabel("NOMBRE: ");
        JLabel email = new JLabel("EMAIL: ");
        JLabel tel = new JLabel("TELEFONO: ");
        JLabel cedula = new JLabel("CEDULA: ");
        JLabel des = new JLabel("MONTO DESCUENTO: ");
        nom.setBounds(0, 20, 60, 20);
        email.setBounds(0, 40, 60, 20);
        tel.setBounds(0, 60, 80, 20);
        cedula.setBounds(0, 80, 60, 20);
        des.setBounds(0, 100, 140, 20);
        panel.add(nom);
        panel.add(tel);
        panel.add(cedula);
        panel.add(email);
        panel.add(des);
    }
    private Control ctrl;
    String INCORRECT = "Cliente no encontrado en el sistema";
    String ERROR = "Error";
    String MENSSAGE = "Digite en los siguientes espacios en blanco los datos del cliente, "
            + "luego presione el boton de insetar";
    String ADVICE = "Consejo";
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Borrado;
    private javax.swing.JButton Busqueda;
    private javax.swing.JButton Inclusion;
    private javax.swing.JButton Modificar;
    private javax.swing.JButton clear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
